name: cd

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Show Lambda directories
        run: |
          echo "Verificando diretórios em 'src/lambdas/':"
          ls -l src/lambdas/ || echo "Nenhum diretório encontrado."

      # Listar todas as lambdas e adicionar na variável
      - name: List all lambdas
        run: |
          # Listar todos os diretórios em src/lambdas e armazenar em uma variável
          LAMBDA_DIRECTORIES=$(find src/lambdas -maxdepth 1 -type d -exec basename {} \;)

          # Exibir as lambdas encontradas
          echo "Lambdas encontradas: $LAMBDA_DIRECTORIES"
          echo "lambdas=$LAMBDA_DIRECTORIES" >> $GITHUB_ENV

      - name: Install Dependencies
        env:
          CI: true
        run: |
          npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Deploy changed lambdas
        run: |
          for lambda in ${{ env.changed_lambdas }}; do
            echo "LAMBDA BUILD AND DEPLOY"
            npx lambda-build upload $lambda -e src/lambdas/$lambda/index.ts -r ${{ secrets.AWS_REGION }}
          done
