name: cd

on:
  push:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Show Lambda directories
        run: |
          echo "Verificando diret칩rios em 'src/lambdas/':"
          ls -l src/lambdas/ || echo "Nenhum diret칩rio encontrado."

      # Listar todas as lambdas e adicionar na vari치vel
      - name: List all lambdas
        run: |
          # Criar o array com os nomes das pastas em src/lambdas
          LAMBDA_ARRAY=( $(ls -d src/lambdas/*/ | xargs -n 1 basename) )

          # Exibir as lambdas encontradas
          echo "Lambdas encontradas: ${LAMBDA_ARRAY[@]}"

          # Definir a vari치vel de ambiente lambdas
          echo "LAMBDA_ARRAY=${LAMBDA_ARRAY[*]}" >> $GITHUB_ENV

      - name: Install Dependencies
        env:
          CI: true
        run: |
          npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build and Deploy changed lambdas
        run: |
          for lambda in "${LAMBDA_ARRAY[@]}"; do
            echo "Deploying $lambda"
            npx lambda-build upload $lambda -e src/lambdas/$lambda/index.ts -r ${{ secrets.AWS_REGION }}
          done
