name: ci

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: install dependencies
        env:
          CI: true
        run: |
          npm ci

      - name:
        run: |
          npm test
