name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '22.11.0'

      - name: Install Dependencies
        env:
          CI: true
        run: |
          npm install

      - name: Run Tests
        run: |
          npm test
