name: Snapshot and Compare PR

on:
  pull_request:
    branches:
      - master

jobs:
  compare-pr:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Checkout da master para garantir que estamos com a versão mais recente da master.
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/master'

      # Passo 2: Armazenar o estado da master antes da PR ser mergeada.
      - name: Get snapshot of master before PR merge
        run: |
          git fetch origin master
          git checkout master
          git reset --hard origin/master  # Faz o reset para garantir que estamos na versão mais recente da master

          # Criar um branch temporário para salvar o estado da master antes da PR
          git checkout -b master-snapshot
          git push https://github.com/${{ github.repository }} master-snapshot

      # Passo 3: Checkout da branch da PR (código da PR).
      - name: Checkout PR branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      # Passo 4: Comparar a master-snapshot com a PR
      - name: Compare changed files between PR and master snapshot
        run: |
          git fetch origin master-snapshot
          git diff --name-only origin/master-snapshot...${{ github.head_ref }} > changed_files.txt
          cat changed_files.txt
