name: Snapshot and Compare PR after Push to Master

on:
  push:
    branches:
      - master # Acontece quando há um push na branch master

jobs:
  compare-pr:
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Fazer o checkout do código mais recente da master.
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: 'refs/heads/master'

      # Passo 2: Criar um commit para capturar o estado da master antes da PR ser mergeada.
      - name: Create snapshot commit for master
        run: |
          git fetch origin master
          git checkout master
          git reset --hard origin/master  # Faz o reset para garantir que estamos na versão mais recente da master

          # Configurar identidade do autor para evitar erro de identidade
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

          # Criar um commit temporário apenas para capturar o estado da master
          git commit --allow-empty -m "Snapshot of master before PR merge"
          git tag master-snapshot  # Criamos uma tag localmente, sem empurrar para o remoto

      # Passo 3: Fazer o checkout do código da branch que foi mesclada na master.
      - name: Checkout PR branch commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.head_commit.id }} # Pega o último commit da branch mesclada

      # Passo 4: Comparar a master-snapshot com o commit da PR
      - name: Compare changed files between PR and master snapshot
        run: |
          # Não é necessário fetch da tag remota, usamos a tag local criada anteriormente
          git diff --name-only refs/tags/master-snapshot...${{ github.event.head_commit.id }} > changed_files.txt
          cat changed_files.txt
